services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=wallamiw
      - MONGO_INITDB_ROOT_PASSWORD=wallamiw
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  # add_products:
  #   build: ./add_products
  #   container_name: add_products
  #   environment:
  #   - PUID=1000
  #   - PGID=1000
  #   ports:
  #     - 81:80
  # vote_products:
  #   image: ./vote_products
  #   container_name: vote_products
  #   environment:
  #   - PUID=1000
  #   - PGID=1000
  #   ports:
  #     - 82:80
  # list_products:
  #   image: ./list_products
  #   container_name: list_products
  #   environment:
  #   - PUID=1000
  #   - PGID=1000
  #   ports:
  #     - 83:80
  buy_products:
    build: ./buy_products/Buy
    container_name: buy_products
    environment:
    - PUID=1000
    - PGID=1000
    ports:
      - 84:80
  # bot:
  #   build: ./bot/TelegramBot
  #   container_name: bot
  #   environment:
  #   - PUID=1000
  #   - PGID=1000
  # web_client:
  #   build: ./web_client/
  #   container_name: web_client
  #   environment:
  #   - PUID=1000
  #   - PGID=1000
  #   ports:
  #     - 8080:80