services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=wallamiw
      - MONGO_INITDB_ROOT_PASSWORD=wallamiw
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  addproducts:
    build: ./add_products/addService
    container_name: addproducts
    environment:
    - PUID=1000
    - PGID=1000
    ports:
      - 81:8080
    restart: "on-failure"
  voteproducts:
    build: ./vote_products/VoteProducts
    container_name: voteproducts
    environment:
    - PUID=1000
    - PGID=1000
    ports:
      - 82:8080
    restart: "on-failure"
  listproducts:
    build: ./list_products/ListProducts
    container_name: listproducts
    environment:
    - PUID=1000
    - PGID=1000
    ports:
      - 83:8080
    restart: "on-failure"
  buyproducts:
    build: ./buy_products/Buy
    container_name: buyproducts
    environment:
    - PUID=1000
    - PGID=1000
    ports:
      - 84:80
    restart: "on-failure"
  bot:
    build: ./bot/TelegramBot
    container_name: bot
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
      - ./data/telegram:/data/db/
    restart: "on-failure"
  front:
    build: ./front/WallaMIW
    container_name: front
    environment:
    - PUID=1000
    - PGID=1000
    ports:
      - 80:8080
    restart: "on-failure"