
package es.uniovi.miw.ws.wallamiw.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IListProductsWS", targetNamespace = "http://webservices.listproducts.ws.miw.uniovi.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IListProductsWS {


    /**
     * 
     * @return
     *     returns java.util.List<es.uniovi.miw.ws.wallamiw.webservices.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listProducts", targetNamespace = "http://webservices.listproducts.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.wallamiw.webservices.ListProducts")
    @ResponseWrapper(localName = "listProductsResponse", targetNamespace = "http://webservices.listproducts.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.wallamiw.webservices.ListProductsResponse")
    @Action(input = "http://webservices.listproducts.ws.miw.uniovi.es/IListProductsWS/listProductsRequest", output = "http://webservices.listproducts.ws.miw.uniovi.es/IListProductsWS/listProductsResponse")
    public List<Product> listProducts();

}
