
package es.uniovi.miw.ws.wallamiw.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVoteProductsWS", targetNamespace = "http://webservices.voteproducts.ws.miw.uniovi.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVoteProductsWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns es.uniovi.miw.ws.wallamiw.webservices.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFavorite", targetNamespace = "http://webservices.voteproducts.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.wallamiw.webservices.AddFavorite")
    @ResponseWrapper(localName = "addFavoriteResponse", targetNamespace = "http://webservices.voteproducts.ws.miw.uniovi.es/", className = "es.uniovi.miw.ws.wallamiw.webservices.AddFavoriteResponse")
    @Action(input = "http://webservices.voteproducts.ws.miw.uniovi.es/IVoteProductsWS/addFavoriteRequest", output = "http://webservices.voteproducts.ws.miw.uniovi.es/IVoteProductsWS/addFavoriteResponse")
    public Product addFavorite(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
