
package es.uniovi.miw.ws.wallamiw.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VoteProductsWSService", targetNamespace = "http://webservices.voteproducts.ws.miw.uniovi.es/", wsdlLocation = "http://voteproducts:8080/voteproducts-1.0-SNAPSHOT/vote_products?wsdl")
public class VoteProductsWSService
    extends Service
{

    private final static URL VOTEPRODUCTSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException VOTEPRODUCTSWSSERVICE_EXCEPTION;
    private final static QName VOTEPRODUCTSWSSERVICE_QNAME = new QName("http://webservices.voteproducts.ws.miw.uniovi.es/", "VoteProductsWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://voteproducts:8080/voteproducts-1.0-SNAPSHOT/vote_products?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOTEPRODUCTSWSSERVICE_WSDL_LOCATION = url;
        VOTEPRODUCTSWSSERVICE_EXCEPTION = e;
    }

    public VoteProductsWSService() {
        super(__getWsdlLocation(), VOTEPRODUCTSWSSERVICE_QNAME);
    }

    public VoteProductsWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOTEPRODUCTSWSSERVICE_QNAME, features);
    }

    public VoteProductsWSService(URL wsdlLocation) {
        super(wsdlLocation, VOTEPRODUCTSWSSERVICE_QNAME);
    }

    public VoteProductsWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOTEPRODUCTSWSSERVICE_QNAME, features);
    }

    public VoteProductsWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VoteProductsWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVoteProductsWS
     */
    @WebEndpoint(name = "VoteProductsWSPort")
    public IVoteProductsWS getVoteProductsWSPort() {
        return super.getPort(new QName("http://webservices.voteproducts.ws.miw.uniovi.es/", "VoteProductsWSPort"), IVoteProductsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVoteProductsWS
     */
    @WebEndpoint(name = "VoteProductsWSPort")
    public IVoteProductsWS getVoteProductsWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.voteproducts.ws.miw.uniovi.es/", "VoteProductsWSPort"), IVoteProductsWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOTEPRODUCTSWSSERVICE_EXCEPTION!= null) {
            throw VOTEPRODUCTSWSSERVICE_EXCEPTION;
        }
        return VOTEPRODUCTSWSSERVICE_WSDL_LOCATION;
    }

}
